### ISSUE TITLE
Can't run pip3 install when running as a non-root user

### ISSUE THREAD

**Issue by carlos-sarmiento** [docker-library/python#414]
I'm trying to install a pip3 package on a container running 3.7-buster with a non-root user. The actual setup is more complicated than shown below, but this is accurate repro.

```
FROM python:3.7-buster

CMD [ "pip3", "install", "integrationhelper==0.2.2"]
```
And I built it with:
```
docker build -t test .
```

If I run with the following command it works:
```
docker run --rm -it test 
```

But if I run it with either of the following:
```
docker run -u 1004:1004 --rm -it test 
docker run -u 1004:1004 --group-add 50 --rm -it test 
```

I get the following error:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/chardet'
Consider using the `--user` option or check the permissions.
```

**Comment by carlos-sarmiento** [comment]
Also tried to run it using `--user` on the image's `CMD`. And it also fails:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/.local'
Check the permissions.
```

**Comment by wglambert** [comment]
A workaround for running as an arbitrary user is to install everything you want in the Dockerfile first. Since the permissions issues are pretty pervasive, most everything is owned by root.

---

I made a Dockerfile with a `chmod -R 777 /usr/local/lib/python3.7/site-packages` and the permissions issue is just propagated further back with a new error
```console
WARNING: Building wheel for yarl failed: [Errno 13] Permission denied: '/.cache'
Failed to build yarl
Installing collected packages: backoff, multidict, idna, yarl, async-timeout, attrs, chardet, aiohttp, integrationhelper
  Running setup.py install for yarl ... done
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/chardetect'
```

But that file isn't even present
```console
$ ls -al /usr/local/bin | grep -i char

$ ls -al /usr/local/bin
total 124
drwxr-xr-x  2 root root  4096 Aug 14 12:11 .
drwxr-xr-x 23 root root  4096 Aug 20 16:36 ..
lrwxrwxrwx  1 root root     8 Aug 14 12:11 2to3 -> 2to3-3.7
-rwxr-xr-x  1 root root   101 Aug 14 12:11 2to3-3.7
-rwxr-xr-x  1 root root   238 Aug 14 12:11 easy_install
-rwxr-xr-x  1 root root   238 Aug 14 12:11 easy_install-3.7
lrwxrwxrwx  1 root root     5 Aug 14 12:11 idle -> idle3
lrwxrwxrwx  1 root root     7 Aug 14 12:11 idle3 -> idle3.7
-rwxr-xr-x  1 root root    99 Aug 14 12:11 idle3.7
-rwxr-xr-x  1 root root   220 Aug 14 12:11 pip
-rwxr-xr-x  1 root root   220 Aug 14 12:11 pip3
-rwxr-xr-x  1 root root   220 Aug 14 12:11 pip3.7
lrwxrwxrwx  1 root root     6 Aug 14 12:11 pydoc -> pydoc3
lrwxrwxrwx  1 root root     8 Aug 14 12:11 pydoc3 -> pydoc3.7
-rwxr-xr-x  1 root root    84 Aug 14 12:11 pydoc3.7
lrwxrwxrwx  1 root root     7 Aug 14 12:11 python -> python3
lrwxrwxrwx  1 root root    14 Aug 14 12:11 python-config -> python3-config
lrwxrwxrwx  1 root root     9 Aug 14 12:11 python3 -> python3.7
lrwxrwxrwx  1 root root    16 Aug 14 12:11 python3-config -> python3.7-config
-rwxr-xr-x  2 root root 36864 Aug 14 12:11 python3.7
lrwxrwxrwx  1 root root    17 Aug 14 12:11 python3.7-config -> python3.7m-config
-rwxr-xr-x  2 root root 36864 Aug 14 12:11 python3.7m
-rwxr-xr-x  1 root root  2894 Aug 14 12:11 python3.7m-config
lrwxrwxrwx  1 root root    10 Aug 14 12:11 pyvenv -> pyvenv-3.7
-rwxr-xr-x  1 root root   441 Aug 14 12:11 pyvenv-3.7
-rwxr-xr-x  1 root root   216 Aug 14 12:11 wheel
```

I could keep `chmod`ing everything to be non-root permissible but this isn't really the right solution for running as an arbitrary user. If you install everything in the Dockerfile I don't think you'd run into many permission issues using the image as non-root

**Comment by tianon** [comment]
Yeah, I think "arbitrary user can run `pip` for global installs" is a bit of a rabbit hole -- I believe the `--user` flag on `pip install` *is* an appropriate one to use here:

```
  --user                      Install to the Python user install directory for
                              your platform. Typically ~/.local/, or
                              %APPDATA%\Python on Windows. (See the Python
                              documentation for site.USER_BASE for full details.)
```

(Possibly also/rather `--root` and/or `--prefix`, but I'm not enough of a "pip expert" to say for sure.)

**Comment by wglambert** [comment]
Going to close since this seems resolved by either installing to the [user's home](https://www.python.org/dev/peps/pep-0370/) or installing in the Dockerfile while still root (not through `CMD`)

**Comment by SpongeManiac** [comment]
I am unable to install pip packages using `--user`, I still get permissions error. I don't want packages installed using the `RUN` directive because I want dependencies to be checked and installed each time the container is run. Are there any solutions to this yet? I have even tried running the python install as user 1000, but that doesn't work either.

**Comment by tianon** [comment]
I can't reproduce a failure -- can you provide more details?

```console
$ docker run -it --rm --pull=always --user 1000:1000 --env HOME=/tmp python sh -c 'pip install --user hy && ~/.local/bin/hy -c "(print (+ 2 2))"'
latest: Pulling from library/python
Digest: sha256:6d7fa2d5653e1d0eb464a672ded01f973e49e4a7ded59703c7bdcf6b92eac736
Status: Image is up to date for python:latest
Collecting hy
  Downloading hy-0.27.0.tar.gz (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.9/100.9 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting funcparserlib~=1.0 (from hy)
  Using cached funcparserlib-1.0.1-py2.py3-none-any.whl (17 kB)
Building wheels for collected packages: hy
  Building wheel for hy (setup.py) ... done
  Created wheel for hy: filename=hy-0.27.0-py3-none-any.whl size=112099 sha256=1b984f54d9bde7ac6c347da7c4077f0954ae8a840c8b1ee340d798be3189e095
  Stored in directory: /tmp/.cache/pip/wheels/d0/26/2d/ab25d6c62ac9c0654c5a8a9dc92a49bfda8a0191f06edf2a3b
Successfully built hy
Installing collected packages: funcparserlib, hy
  WARNING: The scripts hy, hy2py and hyc are installed in '/tmp/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed funcparserlib-1.0.1 hy-0.27.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
4
```
